[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["processthreadsapi", "winnt", "minwindef", "handleapi", "memoryapi", "ntdef", "tlhelp32"] }